id: A90959A54
title: CIII_Mind-only
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:07:01.304368
  last_modified_at: 2022-03-01 23:07:01.304375
