id: A90959A54
title: 'Chapter 2: VimalÄ'
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:07:01.440162
  last_modified_at: 2022-03-01 23:07:01.440165
