id: A90959A54
title: CIII_Verse 6.81-90
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:07:01.385516
  last_modified_at: 2022-03-01 23:07:01.385519
