id: A90959A54
title: CIII_The two truths
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:07:01.309766
  last_modified_at: 2022-03-01 23:07:01.309769
