id: A90959A54
title: CI_Verse 1.11-17
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:07:01.433477
  last_modified_at: 2022-03-01 23:07:01.433481
