id: A90959A54
title: 'Chapter 7: Dūraṃgamā'
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:07:01.446483
  last_modified_at: 2022-03-01 23:07:01.446486
