id: A90959A54
title: CIII_Verse 6.71-80
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:07:01.382696
  last_modified_at: 2022-03-01 23:07:01.382700
