id: A90959A54
title: CIV_Colophon
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:07:01.398399
  last_modified_at: 2022-03-01 23:07:01.398402
