id: A90959A54
title: CIII_Dependent arising
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:07:01.299894
  last_modified_at: 2022-03-01 23:07:01.299901
