id: A90959A54
title: CII_Verse 3.1-10
type: translation
source_metadata:
  languages:
  - bo
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:07:01.391392
  last_modified_at: 2022-03-01 23:07:01.391395
